### ISSUE TITLE
pangenome_alignment.fasta file explanation

### ISSUE THREAD

**Issue by cizydorczyk** [SionBayliss/PIRATE#35]
Hello,

I just wanted to clarify what the pangenome alignment file contains. From my understanding, it contains all genes in the pangenome, concatenated together, with a sequence for each sample in the PIRATE run. Genes are in the same order as in the ordered tsv file. Is this correct?

If so, are the genes concatenated simply end-to-end, or is some spacer used? And how are missing genes handled? "N"s or "-"? I understand that dosage > 1 genes are replaced by "?", but does this refer to all copies of the gene, or subsequent (after the first, however that is defined)?

Thank you!
Conrad

**Comment by SionBayliss** [comment]
Hi Conrad, 

The genes are concatenated end to start (forward orientation) with no spacer. They are printed in the order of the genes in *.ordered.tsv file (default). The GFF denoted the position of each gene. Ambiguous positions, such as multiple potential copies or the same gene, are replaced with a dash ("-") to differentiate them from missing genes or gaps caused by alignment which are denoted with an N (Note: the ? is likely due to an older version of PIRATE). 

There will only ever be one sequence per genome for a gene family. The option --multi-include will include the longest version of multi copy genes instead of replacing them with a dash.

There are some other options in create_pangenome_alignment script that maybe useful.

All the best,
Sion

**Comment by cizydorczyk** [comment]
Great, thank you for the clarification!

**Comment by haruosuz** [comment]
In PIRATE, firstly sequences in each gene_family are aligned at the amino acid level using MAFFT, then backtranslated to nucleotide, and finally multiple alignments are concatenated?

Because "the ? is likely due to an older version of PIRATE", the following two "?s" in README.md should be updated?

https://github.com/SionBayliss/PIRATE/blob/master/README.md

* [optional -a] **core_alignment/pangenome_alignment.fasta** - gene-by-gene nucleotide alignments of the core and full pangenome created using MAFFT. Loci are ordered using the PIRATE.gene_families.ordered.tsv file. If the pangenome was created from translated CDS then the resulting alignments were reverse-translated from the amino acid sequence to retain the codon structure of the genes. **Note** - If a genome has a gene dosage/copy number of >1 for the gene family then the seqeuence is replaced with ?s in the alignment. 

Samples with multiple sequences are by default replaced with a single sequences of ?s.
