### ISSUE TITLE
Adding more genomes to a PIRATE run

### ISSUE THREAD

**Issue by parul-sharma** [SionBayliss/PIRATE#38]
Hi,
I have been using PIRATE for bacterial genomes and was wondering if there is a way to conduct an analysis by adding more genomes to an old run. 
I used it on 130 genomes in the first run and now have to add a few more genomes for the same analysis. From my understanding, it seems like I have to rerun the whole thing with all the genomes, but is there a way around it? 
PS: Really appreciate the PIRATE humor. :)

**Comment by SionBayliss** [comment]
Hi Parul, 

Unfortunately adding genomes to a preexisting run is not currently possible (maybe in the future). I am glad that you have a run with only a small number of genomes so that rerunning it isn't too problematic. If you need to find points of comparison between runs you could just use the locus tags of a single (or set) of genomes. The clustering is not deterministic between runs but should be broadly comparable. 

All the best,
Sion

**Comment by parul-sharma** [comment]
Thanks for getting back to me Dr Bayliss. Really appreciate your response.
