### ISSUE TITLE
Missing --version flag

### ISSUE THREAD

**Issue by tseemann** [SionBayliss/PIRATE#40]
should print to stdout one line:
```
PIRATE 1.0.4
```
and return 0

**Comment by SionBayliss** [comment]
I don't have the same error on my version when running from a local file. However, I do get it from the PIRATE file installed in PATH by conda. This persists even after updating using 'conda update PIRATE'. However, the correct version of the script is available (in which this has been fixed in a previous commit) via PATH on fresh installation with 'conda create -n * PIRATE'. So this looks like a conda issue on updating rather than an issue with the current version of PIRATE. Was this perhaps your experience? Do you have any idea what this could be, I am not that familiar with the conda intall/update process?

**Comment by tseemann** [comment]
@SionBayliss actually it does work in 1.0.3 but it is NOT LISTED IN THE --help :)
