### ISSUE TITLE
[Feature] Make output file with original gene designations from GFF files

### ISSUE THREAD

**Issue by dutchscientist** [SionBayliss/PIRATE#5]
I see the genes have been renumbered by PIRATE. I use Prokka to number the genes and use a 10-step (_00010, _00020 etc), but PIRATE renumbers these and adds the full name to it.

Example:
genome Ec2456_phyloC, gene designations Ec2456_00010 etc

Renamed to: 
genome Ec2456_phyloC, gene designations Ec2456_phyloC_00001 etc

Is it possible to instruct PIRATE not to renumber or rename, and work with the original codes from the GFF files?

**Comment by dutchscientist** [comment]
or is this what subsample_outputs.pl does?

**Comment by SionBayliss** [comment]
Apologies for the late reply.  Yes this is what  subsample_outputs.pl is intended for. You can pass the --field flag with the "prev_locus" argument in order to retrieve the original locus tags from the input files. I have been toying with this being part of the final steps in the pipeline but it has some unintended consequences for some of support scripts.

**Comment by dutchscientist** [comment]
Thanks!
