### ISSUE TITLE
stuck at threshold 60 during MCL clustering

### ISSUE THREAD

**Issue by jiyanxu** [SionBayliss/PIRATE#86]
Hi,

I have installed PIRATE and its dependencies, `PIRATE -c` shows it's no problem. But when I apply to my own test data (gff, annotated by prokka), at the beginning everything is fine, when it comes to MCL clustering:

-- running mcl on pan_sequences at 50
-- 3824 clusters at 50% - completed in 37 secs
-- running mcl on pan_sequences at 60

Then I never get further results.
I checked the statue in `htop`, it is always `D` 

How do you think? I really need your help.

All the best

**Comment by SionBayliss** [comment]
Hi, 

This seems more likely to be a system issue than one caused by the software. My limited understanding is that state D in htop has to do with memory I/O issue. Could your disk be slow or otherwise overloaded. Have you tried running the dataset on a different device? Please let me know if that resolves the issue. 

All the best,
Sion

**Comment by jiyanxu** [comment]
Hi Sion,

thank you very much for the reply! I would try on another device and let you know.

All the best,
Jiyan

**Comment by jiyanxu** [comment]
Dear Sion,

I successfully got the result when the HPC was not highly demanded. Thank you very much for the timely reply!

All the best,
Jiyan
